package com.iSteer.prakadesh.enums;

public enum MfaEnum {

	USER_ADDED_SUCCESSFULLY(1001, " USER ADDED SUCCESSFULLY"), 
	USER_FOUND_EXCEPTION(1002, " USER FOUND! USER VERIFIED"),
	USER_NOT_ADDED(9001, " THIS OPERATION CANNOT BE DONE. USER ALREADY EXISTS"), 
	USER_NOT_FOUND(9002, "USER NOT FOUND"),
	ANSWER_CHECK(9005, " CURRENT ANSWER DOES NOT MATCH THE OLD ANSWER"),
	ANSWER_NULL_OR_EMPTY(9105, "ANSWER SHOULD NOT BE NULL OR EMPTY"),
	ANSWER_INCORRECT(9205," YOUR ANSWER IS INCORRECT "),
	GET_NEW_ANSWER_FOR_UPDATE(9305, " NEW ANSWER CANNOT BE NULL OR BLANK OR INVAILD "),
	GET_OLD_ANSWER_FORUPDATE(9405, " NEW ANSWER CANNOT BE SAME AS OLD ANSWER"),
	MARKER_NOT_FOUND_EXCEPTION(9000, " PLEASE GET THE QUESTION FOR, CONTINUE THE OPERATION"),
	QUESTION_NOT_FOUND_EXCEPION(9505, "YOUR CURRENT QUESTION IS NOT FOUND"),
	UPDATE_FAILED_EXCEPTION(9605, "THIS OPERATION CANNOT BE DONE, FILL THE REQUIRED FIELDS"),
	UPDATE_SUCCESS_EXCEPTION(1003, " UPDATE OPERATION SUCCESSFULL"),
	USER_ID_NULL_EMPTY_EXCEPTION(9234, " USER ID CANNOT BE NULL OR EMPTY OR INVAILD"),
	VALIDATION_FAILED(9474, " VALIDATION IS FAILED"), VALIDATION_SUCCESS(1004, "VALIDATION IS SUCCESSFULL"),
	QUESTION_NULL_EMPTY_OR_INVAILD(9705," QUESTION CANNOT BE NULL OR EMPTY OR INVAILD "),
	DATA_VALIDATION_EXCEPTION(9012," INVAILD INPUT "),
	ROLE_FIELD_EXCEPTION(9991," PLEASE REGISTER WITH APPROPIRATE ROLE 'Admin' or 'User' "),
	 Admin_duplicate_entry_exception(9992," THE CUSTOMER IS ALREADY IN THE ROLE YOUR TRYING TO CHANGE "),
	 PASSWORD_INVAILD_EXCEPTION(9993,"ENTER THE CORRECT PASSWORD"), 
	 Access_Denied_Exception(9876,"Only Admin can access this resource.");
	
	int statusCode;
	String statusMessage;

	MfaEnum(int statusCode, String statusMessage) {
		this.statusCode = statusCode;
		this.statusMessage = statusMessage;
	}

	public int getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(int statusCode) {
		this.statusCode = statusCode;
	}

	public String getStatusMessage() {
		return statusMessage;
	}

	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}

}
